spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db/migration
management:
  endpoints:
    web:
      base-path: /
graphql:
  packages: org.misarch.user
  federation:
    enabled: true